general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window] 
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = 'JetBrainsMono Nerd Font Mono'
size = 14


